### ISSUE TITLE
Add a description to the repository

### ISSUE THREAD

**Issue by derekstavis** [oh-my-fish/theme-cmorrell.com#5]
Oh My Fish uses Github API to fetch repository descriptions with `omf describe`. Adding a description to this project would be nice!

**Comment by inxilpro** [comment]
Hmm. Doesn't look like I have access to update. Here's a description if someone wants to update:

> Theme with minimal base prompt, compact git status, and useful visual indicators for common scenarios.

**Comment by bpinto** [comment]
@inxilpro You should have total access to this repository. This was just granted, sorry for that.

**Comment by inxilpro** [comment]
Updated.

**Comment by derekstavis** [comment]
:+1:
